[EBYTE_E77]
extends = stm32_base
board = ebyte_e77_dev
board_upload.maximum_size = 229376 ; 32kb for FS
board_level = extra
build_flags = ${stm32_base.build_flags}
  -D RADIO_CLASS=CustomSTM32WLx
  -D WRAPPER_CLASS=CustomSTM32WLxWrapper
  -D SPI_INTERFACES_COUNT=0
  -D RX_BOOSTED_GAIN=true
  -D STM32WL_TCXO_VOLTAGE=1.6 ; defaults to 0 if undef
;  -D LORA_TX_POWER=14 ; Defaults to 22 for HP, 14 is for LP version
  -I variants/EBYTE_E77
build_src_filter = ${stm32_base.build_src_filter}
  +<../variants/EBYTE_E77>

[env:E77_repeater]
extends = EBYTE_E77
build_flags = ${EBYTE_E77.build_flags}
  -D ADVERT_NAME='"E77 Repeater"'
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter = ${EBYTE_E77.build_src_filter}
  +<../examples/simple_repeater/*.cpp>

[env:E77_sensor]
extends = EBYTE_E77
build_flags = ${EBYTE_E77.build_flags}
  -D ADVERT_NAME='"E77 Sensor"'
  -D ADMIN_PASSWORD='"password"'
build_src_filter = ${EBYTE_E77.build_src_filter}
  +<../examples/simple_sensor>

[env:E77_companion_radio_usb]
extends = EBYTE_E77
build_flags = ${EBYTE_E77.build_flags}
;  -D FORMAT_FS=true
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
build_src_filter = ${EBYTE_E77.build_src_filter}
  +<../examples/companion_radio/*.cpp>
lib_deps = ${EBYTE_E77.lib_deps}
  densaugeo/base64 @ ~1.4.0
